### ISSUE TITLE
感谢及时修复启动问题，另外可否增加一个测试说明的例子项页面呢？

### ISSUE THREAD

**Issue by openwrtdiy** [Hyy2001X/luci-app-iperf3-server#1]
iperf3 当前有很多测试参数，搜索各不一样。如果能搞个子项页把常用的测试参数列出，那样可以很方便进行相关测试。

增加的页面可以像NFT-QoS 设置的界面增加一个例子选项。
![下载](https://user-images.githubusercontent.com/57249132/129342594-1b08537f-9f14-4185-858a-7c8079c902e8.jpg)

**Comment by Hyy2001X** [comment]
感谢你的建议，列出常用参数的这个功能我得研究一下，写这个界面还比较萌新

**Comment by openwrtdiy** [comment]
下面这些常用命令参数是我平时网上找的，理解命令参数这些也很头疼的事。另外中英文界面的翻译跟OpenWrt官方.po 适当套一下，当前少了两个标配语言文件：templates/iperf3-server.pot 和 zh_Hans/iperf3-server.po
还有一个消息是OpenWrt官方现时也在做iperf3 服务端UCI命令支持，你可以了解他们的一些新命令一下。
https://github.com/openwrt/packages/pull/16282
https://github.com/openwrt/luci/pull/4651


服务器命令
iperf3 -s


单线测试命令：

iperf3 -c 192.168.100.1 -b 100m -t 60 -i 1 -u

iperf3 -c 192.168.100.1 -b 1000m -t 60 -i 1 -u

iperf3 -c 192.168.100.1 -b 100m -t 60 -i 1 -u

iperf3 -c 192.168.100.1 -b 1000m -t 60 -i 1 -u

-c表示运行的是客户端模式，就是测速发送方。 -b表示估计带宽，-t表示持续测速时间，就是一共跑60秒，-i表示间隔输出结果时间，就是每隔1秒钟输出一次，-u表示使用udp连接来测速，默认是tcp连接测速，因为tcp要进行确认所以不如udp测速更准确。当然这里默认使用了单线程


多线测试命令：

iperf3 -c 192.168.100.1 -b 100m -t 60 -i 1 -u -P 2

多线程，2-4个最好，太多了路由器吃不消


显示版本信息并退出
iperf3 -v
